# Generated by Django 5.1.4 on 2024-12-20 21:54

import certificado.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0015_rename_funcao_cargo_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('validade_meses', models.PositiveIntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='funcionario.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateField()),
                ('validade_final', models.DateField(editable=False)),
                ('arquivo', models.FileField(upload_to=certificado.models.upload_to_funcionario)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificado.certificado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_certificados_atual', to='funcionario.funcionario')),
            ],
        ),
    ]
