# Generated by Django 5.1.4 on 2024-12-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('matricula', models.IntegerField(max_length=10000, unique=True)),
                ('data_admissao', models.DateField()),
            ],
        ),
    ]
