# Generated by Django 5.1.4 on 2024-12-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='colaborador',
        ),
    ]
