# Generated by Django 5.1.4 on 2024-12-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0012_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='funcao',
            new_name='nome',
        ),
    ]
