# Generated by Django 5.1.4 on 2024-12-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0013_rename_funcao_cargo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='nome',
            new_name='funcao',
        ),
    ]
