# Generated by Django 5.1.4 on 2024-12-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0014_rename_nome_cargo_funcao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='funcao',
            new_name='nome',
        ),
    ]
